# Generated by Django 3.2.4 on 2021-06-17 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('idRelacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Relación')),
                ('nombreRelacion', models.CharField(max_length=80, verbose_name='Nombre de la relación')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellido')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='Contraseña')),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.relacion')),
            ],
        ),
    ]
